#45 Be cautious about deleting in configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -37,7 +37,8 @@ elif [ "$UNAME" = "Cygwin" ];
 then
   UNAME_CYGWIN=1
 else
-  echo "Invalid uname ($UNAME): Unsuppported platform"
+  echo "Invalid uname ($UNAME): Unsuppported platform" 1>&2
+  exit 1
 fi
 
 # Colors
@@ -134,14 +135,14 @@ pushd glfw-rs
     if [ "0" -eq "$UNAME_LINUX" -o "0" -eq "$UNAME_CYGWIN" ];
     then
       # Linux
-      rm -f $BWD/../*.so
+      rm -f $BWD/../libglfw-*.so
       for file in `find build -name '*.so'`; do
         cp $file $BWD/../
       done
     elif [ "0" -eq "$UNAME_OSX" ];
     then
       # Mac
-      rm -f $BWD/../*.dylib
+      rm -f $BWD/../libglfw-*.dylib
       for file in `find build -name '*.dylib'`; do
         cp $file $BWD/../
       done
